### ISSUE TITLE
Set up testing and code coverage reports

### ISSUE THREAD

**Issue by Codel1417** [OpenTails/tail_app#204]
Codecov token already set up. Need to create test action which sets up the environment and runs flutter test

```yml
- name: Upload coverage reports to Codecov
    uses: codecov/codecov-action@v4.0.1
    with:
      token: ${{ secrets.CODECOV_TOKEN }}
```

- [x] Create testing job
- [x] Configure basic unit testing in flutter
- [x] achieve 10% code coverage
- [ ]  achieve 20% code coverage

The end goal would be 100% coverage, but 10% is just a start. 

https://docs.flutter.dev/testing/overview
https://app.codecov.io/gh/OpenTails/tail_app/new
